Building imgtool no longer causes a linker error because of an "undefined reference to `floor'".  I don't know why, but I only saw it with debug builds. Cleaned up a few lines.